name: Nx Smart CI

on:
  push:
    branches:
      - main
      - dev
      - staging

jobs:
  affected:
    runs-on: ubuntu-latest
    outputs:
      affected_apps: ${{ steps.affected.outputs.apps }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Nx CLI & jq
        run: npm install -g nx jq

      - name: Determine affected projects
        id: affected
        run: |
          AFFECTED=$(npx nx show projects --affected --base=origin/main --head=HEAD --json | jq -c 'select(. != null)')

          if [[ -z "$AFFECTED" ]]; then
            echo "No affected projects detected."
            echo "apps=[]" >> "$GITHUB_OUTPUT"
          else
            echo "Affected projects: $AFFECTED"
            echo "apps=$AFFECTED" >> "$GITHUB_OUTPUT"
          fi

  deploy:
    needs: affected
    runs-on: ubuntu-latest
    if: ${{ needs.affected.outputs.affected_apps != '[]' }} # ✅ Skip if no affected apps
    strategy:
      matrix:
        app: ${{ fromJson(needs.affected.outputs.affected_apps) }}
    name: 🚀 Deploy ${{ matrix.app }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy ${{ matrix.app }}
        run: |
          echo "🚀 Deploying ${{ matrix.app }}..."
          npx nx build ${{ matrix.app }}
